### ISSUE TITLE
Scrolling on slider does not work on touch screen devices

### ISSUE THREAD

**Issue by rayonx** [ScoopThemes/scoopthemes.github.io#1]
I have tried to view Oleose Theme on my android tablet and phone, the scrolling vertically does not work on both devices for some reason, I have tried to change the settings of the revolution slider by changing the  "touchenabled" flag to "on" as well as "off", but it doesn't make a difference. Any solution to this issue ? Thanks

**Comment by mshaaban0** [comment]
Wrong Repo , I Think you mean Oleose Theme already Fixed
